//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerDEID.Common.Globals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlServerDEID.Common.Globals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [a].[table_view],
        ///    [a].[object_type],
        ///    [a].[constraint_type],
        ///    [a].[constraint_name],
        ///    [a].[details]
        ///FROM (
        ///    SELECT
        ///        SCHEMA_NAME([t].[schema_id]) + &apos;.&apos; + [t].[name] AS [table_view],
        ///        CASE
        ///            WHEN [t].[type] = &apos;U&apos; THEN &apos;Table&apos;
        ///            WHEN [t].[type] = &apos;V&apos; THEN &apos;View&apos;
        ///        END AS [object_type],
        ///        CASE
        ///            WHEN [c].[type] = &apos;PK&apos; THEN &apos;Primary key&apos;
        ///            WHEN [c].[type] = &apos;UQ&apos; THEN &apos;Unique constraint&apos;
        ///            WHEN [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetConstraints {
            get {
                return ResourceManager.GetString("GetConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    CONCAT(QUOTENAME(SCHEMA_NAME([t].[schema_id])), &apos;.&apos;, QUOTENAME([t].[name])) AS [table_name],
        ///    [c].[name] AS [column_name],
        ///    [c].[type_name],
        ///    [c].[max_length],
        ///    [c].[precision],
        ///    [c].[scale],
        ///    [c].[is_nullable],
        ///    [c].[is_identity],
        ///    [c].[is_computed],
        ///    [c].[is_pk],
        ///    [c].[pk_ordinal]
        ///FROM [sys].[tables] AS [t]
        ///INNER JOIN (
        ///    SELECT
        ///        [c].[name],
        ///        [c].[column_id],
        ///        [c].[object_id],
        ///        [typ].[type_name],
        ///        CASE
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTableMetaData {
            get {
                return ResourceManager.GetString("GetTableMetaData", resourceCulture);
            }
        }
    }
}
